# Material table
INSERT INTO MATERIAL VALUES (NULL, "Stoffa");
INSERT INTO MATERIAL VALUES (NULL, "Plastica");
INSERT INTO MATERIAL VALUES (NULL, "Ferro");
INSERT INTO MATERIAL VALUES (NULL, "Metallo");
INSERT INTO MATERIAL VALUES (NULL, "Tela");

# Sport table
INSERT INTO SPORT VALUE (NULL, "Calcio");
INSERT INTO SPORT VALUE (NULL, "Judo");
INSERT INTO SPORT VALUE (NULL, "Canoa");
INSERT INTO SPORT VALUE (NULL, "Ballo");
INSERT INTO SPORT VALUE (NULL, "Basket");
INSERT INTO SPORT VALUE (NULL, "Pallavolo");
INSERT INTO SPORT VALUE (NULL, "Nuoto");

# Shop table
INSERT INTO SHOP VALUES ("MHGYSP80E61H098F", "Amazon", "Via Universita", "Verona");
INSERT INTO SHOP VALUES ("CNFRLY45D56D365Q", "Google", "Via Mario", "Verona");
INSERT INTO SHOP VALUES ("CRBLHM32C51M143A", "Poli", "Via Luigi", "Trento");

# Bill table
INSERT INTO BILL VALUES (NULL, "Fattura nr.1");
INSERT INTO BILL VALUES (NULL, "Fattura nr.2");
INSERT INTO BILL VALUES (NULL, "Fattura nr.3");
INSERT INTO BILL VALUES (NULL, "Fattura nr.4");

# Courier table
INSERT INTO COURIER VALUES (NULL, "Bartolini");
INSERT INTO COURIER VALUES (NULL, "TNT");
INSERT INTO COURIER VALUES (NULL, "SDA");
INSERT INTO COURIER VALUES (NULL, "Amazon");
INSERT INTO COURIER VALUES (NULL, "Poste Italiane");

# Warehouse_out table
# bill, shop, courier
INSERT INTO WAREHOUSE_OUT VALUES (NULL, 1, "MHGYSP80E61H098F", 1);
INSERT INTO WAREHOUSE_OUT VALUES (NULL, 1, "MHGYSP80E61H098F", 1);
INSERT INTO WAREHOUSE_OUT VALUES (NULL, 2, "CNFRLY45D56D365Q", 2);
INSERT INTO WAREHOUSE_OUT VALUES (NULL, 2, "CNFRLY45D56D365Q", 2);
INSERT INTO WAREHOUSE_OUT VALUES (NULL, 3, "CRBLHM32C51M143A", 2);

# Orders table
INSERT INTO ORDERS VALUES (NULL, 1, "2018-04-01");
INSERT INTO ORDERS VALUES (NULL, 1, "2018-04-02");
INSERT INTO ORDERS VALUES (NULL, 2, "2018-04-03");
INSERT INTO ORDERS VALUES (NULL, 3, "2018-04-05");
INSERT INTO ORDERS VALUES (NULL, 5, "2018-04-04");

# Article table
INSERT INTO ARTICLE_TYPE VALUES (NULL, "Scarpa", "Scarpa da ginnastica", 4, 1);
INSERT INTO ARTICLE_TYPE VALUES (NULL, "Scarpa", "Scarpa da ginnastica", 4, 4);
INSERT INTO ARTICLE_TYPE VALUES (NULL, "Pallone", "Pallone da pallavolo", 5, 1);
INSERT INTO ARTICLE_TYPE VALUES (NULL, "Pallone", "Pallone da pallavolo", 5, 1);
INSERT INTO ARTICLE_TYPE VALUES (NULL, "Canoa", "Canona lunga", 2, 2);

# Order_detail table
INSERT INTO ORDER_DETAIL VALUES (NULL, 1, 2, 3, "12");
INSERT INTO ORDER_DETAIL VALUES (NULL, 3, 2, 4, "24");

# Warehouse_in
INSERT INTO WAREHOUSE_IN VALUES (NULL, "2018-04-01", "Arco", 1);
INSERT INTO WAREHOUSE_IN VALUES (NULL, "2018-04-01", "Arco", 2);
INSERT INTO WAREHOUSE_IN VALUES (NULL, "2018-04-01", "Arco", 4);

# Article table
INSERT INTO ARTICLE VALUES (NULL, 1, "13", "2018-04-01");
INSERT INTO ARTICLE VALUES (NULL, 2, "23", "2018-04-01");
INSERT INTO ARTICLE VALUES (NULL, 1, "33", "2018-04-02");

# User table
INSERT INTO USER VALUES (NULL, 1010, "fabio", AES_ENCRYPT("chiarani","726F328BB97BFF5529B9771ABC5FECDD"));
INSERT INTO USER VALUES (NULL, 1010, "luigi", AES_ENCRYPT("capogrosso","726F328BB97BFF5529B9771ABC5FECDD"));