#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Dec 29 17:11:56 CET 2019
# SW Build 2644227 on Wed Sep  4 09:44:18 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_time_synth -key {Post-Synthesis:sim_1:Timing:tb} -tclbatch tb.tcl -log simulate.log"
xsim tb_time_synth -key {Post-Synthesis:sim_1:Timing:tb} -tclbatch tb.tcl -log simulate.log

