# AES: https://dev.mysql.com/doc/refman/5.5/en/encryption-functions.html#function_aes-decrypt


drop database nomeDatabase;
create database nomeDatabase;

use nomeDatabase;

CREATE TABLE MATERIAL (
    idMateriale INTEGER AUTO_INCREMENT NOT NULL,
    description varchar(100),
    PRIMARY KEY (idMateriale)
);

CREATE TABLE SPORT (
    idSport INTEGER AUTO_INCREMENT NOT NULL,
    description varchar(100),
    PRIMARY KEY (idSport)
);

CREATE TABLE SHOP (
    cfShop varchar(50) NOT NULL,
    name varchar(100) NOT NULL,
    street varchar(200) NOT NULL,
    position varchar(200) NOT NULL,
    PRIMARY KEY (cfShop)
);

CREATE TABLE BILL (
    idBill INTEGER AUTO_INCREMENT NOT NULL,
    description varchar(200),
    PRIMARY KEY (idBill)
);

CREATE TABLE COURIER (
    idCourier INTEGER AUTO_INCREMENT NOT NULL,
    description varchar(200),
    PRIMARY KEY (idCourier)
);

CREATE TABLE WAREHOUSE_OUT (
    idWarehouseOut INTEGER AUTO_INCREMENT NOT NULL,
    idBill INTEGER NOT NULL,
    cfShop varchar(50) NOT NULL,
    idCourier INTEGER NOT NULL,
    PRIMARY KEY (idWarehouseOut),
    FOREIGN KEY (idBill) REFERENCES BILL (idBill),
    FOREIGN KEY (cfShop) REFERENCES SHOP (cfShop),
    FOREIGN KEY (idCourier) REFERENCES COURIER (idCourier)
);

CREATE TABLE ORDERS (
    idOrder INTEGER AUTO_INCREMENT NOT NULL,
    idWarehouseOut INTEGER NOT NULL,
    date DATETIME NOT NULL,
    PRIMARY KEY (idOrder),
    FOREIGN KEY (idWarehouseOut) REFERENCES WAREHOUSE_OUT (idWarehouseOut)
);

CREATE TABLE ARTICLE_TYPE (
    idArticleType INTEGER AUTO_INCREMENT NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(100) NOT NULL,
    idSport INTEGER NOT NULL,
    idMateriale INTEGER NOT NULL,
    PRIMARY KEY (idArticleType),
    FOREIGN KEY (idSport) REFERENCES SPORT (idSport),
    FOREIGN KEY (idMateriale) REFERENCES MATERIAL (idMateriale)
);

CREATE TABLE ORDER_DETAIL (
    idOrderDetail INTEGER AUTO_INCREMENT NOT NULL,
    idOrder INTEGER NOT NULL,
    idArticleType INTEGER NOT NULL,
    value INTEGER NOT NULL,
    price DOUBLE NOT NULL,
    PRIMARY KEY (idOrderDetail),
    FOREIGN KEY (idOrder) REFERENCES ORDERS (idOrder),
    FOREIGN KEY (idArticleType) REFERENCES ARTICLE_TYPE (idArticleType)
);

CREATE TABLE WAREHOUSE_IN (
    idInternalCode INTEGER AUTO_INCREMENT NOT NULL,
    date DATETIME NOT NULL,
    position varchar(100) NOT NULL,
    idArticleType INTEGER NOT NULL,
    PRIMARY KEY (idInternalCode),
    FOREIGN KEY (idArticleType) REFERENCES ARTICLE_TYPE (idArticleType)
);

CREATE TABLE ARTICLE (
    idArticle INTEGER AUTO_INCREMENT NOT NULL,
    idArticleType INTEGER NOT NULL,
    price DOUBLE NOT NULL,
    date DATETIME NOT NULL,
    PRIMARY KEY (idArticle),
    FOREIGN KEY (idArticleType) REFERENCES ARTICLE_TYPE (idArticleType)
);

CREATE TABLE REPORT (
    idReport INTEGER AUTO_INCREMENT NOT NULL,
    date DATETIME NOT NULL,
    warehouseIn INTEGER NOT NULL,
    warehouseOut INTEGER NOT NULL,
    PRIMARY KEY (idReport) 
);

CREATE TABLE LOG (
    idLog INTEGER AUTO_INCREMENT NOT NULL,
    idUser INTEGER,
    action varchar(250),
    description varchar(250),
    date DATETIME NOT NULL,
    PRIMARY KEY (idLog)
);

CREATE TABLE USER (
    idUser INTEGER AUTO_INCREMENT NOT NULL,
    userType INTEGER NOT NULL,
    name varchar (100) NOT NULL,
    pwd varchar(255) NOT NULL,
    PRIMARY KEY (idUser)
);

# Material table
INSERT INTO MATERIAL VALUES (NULL, "Stoffa");
INSERT INTO MATERIAL VALUES (NULL, "Plastica");
INSERT INTO MATERIAL VALUES (NULL, "Ferro");
INSERT INTO MATERIAL VALUES (NULL, "Metallo");
INSERT INTO MATERIAL VALUES (NULL, "Tela");

# Sport table
INSERT INTO SPORT VALUE (NULL, "Calcio");
INSERT INTO SPORT VALUE (NULL, "Judo");
INSERT INTO SPORT VALUE (NULL, "Canoa");
INSERT INTO SPORT VALUE (NULL, "Ballo");
INSERT INTO SPORT VALUE (NULL, "Basket");
INSERT INTO SPORT VALUE (NULL, "Pallavolo");
INSERT INTO SPORT VALUE (NULL, "Nuoto");

# Shop table
INSERT INTO SHOP VALUES ("MHGYSP80E61H098F", "Amazon", "Via Universita", "Verona");
INSERT INTO SHOP VALUES ("CNFRLY45D56D365Q", "Google", "Via Mario", "Verona");
INSERT INTO SHOP VALUES ("CRBLHM32C51M143A", "Poli", "Via Luigi", "Trento");

# Bill table

# Courier table
INSERT INTO COURIER VALUES (NULL, "Bartolini");
INSERT INTO COURIER VALUES (NULL, "TNT");
INSERT INTO COURIER VALUES (NULL, "SDA");
INSERT INTO COURIER VALUES (NULL, "Amazon");
INSERT INTO COURIER VALUES (NULL, "Poste Italiane");
INSERT INTO COURIER VALUES (NULL, "UPS");

# Warehouse_out table
# bill, shop, courier
INSERT INTO WAREHOUSE_OUT VALUES (NULL, 1, "MHGYSP80E61H098F", 1);
INSERT INTO WAREHOUSE_OUT VALUES (NULL, 1, "MHGYSP80E61H098F", 1);
INSERT INTO WAREHOUSE_OUT VALUES (NULL, 2, "CNFRLY45D56D365Q", 2);
INSERT INTO WAREHOUSE_OUT VALUES (NULL, 2, "CNFRLY45D56D365Q", 2);
INSERT INTO WAREHOUSE_OUT VALUES (NULL, 3, "CRBLHM32C51M143A", 2);

# Orders table
INSERT INTO ORDERS VALUES (NULL, 1, "2018-04-01");
INSERT INTO ORDERS VALUES (NULL, 1, "2018-04-02");
INSERT INTO ORDERS VALUES (NULL, 2, "2018-04-03");
INSERT INTO ORDERS VALUES (NULL, 3, "2018-04-05");
INSERT INTO ORDERS VALUES (NULL, 5, "2018-04-04");

# Article table
INSERT INTO ARTICLE_TYPE VALUES (NULL, "Scarpa", "Scarpa da ginnastica", 4, 4);
INSERT INTO ARTICLE_TYPE VALUES (NULL, "Pallone", "Pallone da pallavolo", 5, 1);

# Order_detail table
INSERT INTO ORDER_DETAIL VALUES (NULL, 1, 2, 3, "12");
INSERT INTO ORDER_DETAIL VALUES (NULL, 3, 2, 4, "24");

# Warehouse_in
INSERT INTO WAREHOUSE_IN VALUES (NULL, "2018-04-01", "Sccafale 1", 1);
INSERT INTO WAREHOUSE_IN VALUES (NULL, "2018-04-01", "Sccafale 1", 2);
INSERT INTO WAREHOUSE_IN VALUES (NULL, "2018-04-01", "Sccafale 2", 4);

# Article table
INSERT INTO ARTICLE VALUES (NULL, 1, "13", "2018-04-01");
INSERT INTO ARTICLE VALUES (NULL, 2, "23", "2018-04-01");

# User table
INSERT INTO USER VALUES (NULL, 1010, "fabio", AES_ENCRYPT("chiarani","F45EF73E453A6E69E7230205EF95992A"));
INSERT INTO USER VALUES (NULL, 2020, "luigi", AES_ENCRYPT("capogrosso","F45EF73E453A6E69E7230205EF95992A"));
INSERT INTO USER VALUES (NULL, 3030, "univr", AES_ENCRYPT("univr","F45EF73E453A6E69E7230205EF95992A"));